### ISSUE TITLE
503 on https://keychecker.trufflesecurity.com/publickey

### ISSUE THREAD

**Issue by sinnwise** [trufflesecurity/driftwood#11]
**Describe the bug**

Currently when you run `driftwood`, it loops within the [main client for loop](https://github.com/trufflesecurity/driftwood/blob/7c2a0e4b9a9020df12e1e5f83d1f2478b543ab32/pkg/exp/client/client.go#L31) and then doesn't ever exit.

This is because `driftwood` doesn't throw a fatal exception during the loop and exit upon receiving a non HTTP-OK response.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run driftwood against any private key 

**Expected behavior**
The program:
- doesn't loop when receiving non-OK HTTP response patterns

The API:
- doesn't 503

**Screenshots**
![Screenshot 2023-03-28 at 13 55 24](https://user-images.githubusercontent.com/122354532/228242931-70cb81bc-2ee3-4e75-97a9-d709584ce9d5.png)

**Desktop (please complete the following information):**
- All versions

**Additional context**
Let me know if you want a PR for adding non-ok pattern matching

**Comment by dustin-decker** [comment]
This is resolved.
