### ISSUE TITLE
lack of knowledge

### ISSUE THREAD

**Issue by CR4ZYHUNT** [trufflesecurity/driftwood#2]
I dont know how to run the tool after I installed it

**Comment by dustin-decker** [comment]
Just run `driftwood path/to/privatekey.pem`

You can see other options with the `--help` flag.

**Comment by CR4ZYHUNT** [comment]
Hi I try to use the command directly after installing the tool but it give
me " command not found error ",
I'm sorry but could u give me the right steps to install the tool from the
start till using it

**Comment by dustin-decker** [comment]
You would need to copy the file to one of your PATH locations for it to be discovered.
Or, you can run the local binary from the current directory like `./driftwood path/to/privatekey.pem`

**Comment by CR4ZYHUNT** [comment]
[image: Screenshot from 2021-11-08 08-04-13.png]
my problem is that there isn't any file called driftwood so I can't use the
command ./driftwood

**Comment by dustin-decker** [comment]
You need to extract the release archive, then you will have a driftwood binary. You'll need to run the command I gave you from that folder.
